import { createAsyncThunk, createSlice, createEntityAdapter } from '@reduxjs/toolkit';
import { RootState } from '../';
import { fetchArtists, ArtistsRawData, ArtistData } from '../helpers';
export interface InitialState {
  pages: ArtistsRawData["data"]["artists"]["@attr"] | null;
  status: 'idle' | 'loading' | 'failed';
}

const initialState: InitialState = {
  pages: null,
  status: 'idle',
};


const artistAdapter = createEntityAdapter<ArtistData>({
    selectId: (artist) => artist.mbid,
});

export const fetchArtistsAsync = createAsyncThunk(
  'artist/fetch',
  async () => {
    const response = await fetchArtists();
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const artistsSlice = createSlice({
  name: 'artists',
  initialState: {
    ...artistAdapter.getInitialState(),
    ...initialState
  },
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchArtistsAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchArtistsAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.pages = action.payload.artists['@attr'];
        artistAdapter.setAll(state, action.payload.artists.artist);
      })
      .addCase(fetchArtistsAsync.rejected, (state) => {
        state.status = 'failed';
      });
  },
});

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
export const selectArtists = (state: RootState) => Object.values(state.artists.entities) as Array<ArtistData>


export default artistsSlice.reducer;
